version: "4.0"

services:
  render-postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5433:5432'
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - audio-main-service-network
  main-postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - audio-main-service-network
  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"
    networks:
      - audio-main-service-network
  minio:
    image: minio/minio
    restart: always
    volumes:
      - minio-storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    networks:
      - audio-main-service-network

networks:
  audio-main-service-network:

volumes:
  postgres-storage:
  minio-storage: